import { createDeck, toggleDeck } from "@/app/admin/predictions/actions";
import { getDatabase } from "@/lib/db/client";
import { requireManagementAdmin } from "@/lib/auth/authorization";

export const dynamic = "force-dynamic";
const input = "mt-2 h-11 w-full rounded-sharp border border-line px-3 text-sm outline-none focus:border-blue focus:ring-4 focus:ring-blue/10";

export default async function AdminDecksPage() {
  await requireManagementAdmin();
  const decks = await getDatabase().deck.findMany({ include: { _count: { select: { predictions: true } } }, orderBy: { sortOrder: "asc" } });
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-7 sm:py-10"><div><h1 className="text-4xl font-semibold tracking-[-0.05em] text-ink">Decks</h1></div><div className="mt-9 grid gap-7 lg:grid-cols-[0.9fr_1.1fr]"><form action={createDeck} className="h-fit rounded-sharp border border-line bg-white p-6"><h2 className="text-xl font-semibold text-ink">Create a Deck</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold text-ink-2">Name<input name="name" required className={input} /></label><label className="text-sm font-bold text-ink-2">Icon<input name="icon" placeholder="VIP" className={input} /></label><label className="text-sm font-bold text-ink-2 sm:col-span-2">Description<textarea name="description" required minLength={10} rows={4} className="mt-2 w-full rounded-sharp border border-line p-3 text-sm outline-none focus:border-blue" /></label><label className="text-sm font-bold text-ink-2">Visual ID<input name="visualIdentifier" placeholder="blue" className={input} /></label><label className="text-sm font-bold text-ink-2">Sort order<input name="sortOrder" type="number" min="0" defaultValue="0" className={input} /></label><label className="flex items-center gap-3 text-sm font-bold text-ink-2 sm:col-span-2"><input name="isPremium" type="checkbox" className="size-4 accent-blue" />Premium Deck</label></div><button className="mt-6 min-h-11 w-full rounded-sharp bg-[var(--color-blue)] text-sm font-semibold text-white">Create Deck</button></form><div className="space-y-4">{decks.map((deck) => <article key={deck.id} className="rounded-sharp border border-line bg-white p-6"><div className="flex items-start justify-between gap-5"><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold text-ink">{deck.name}</h2>{deck.isPremium && <span className="rounded-full bg-hold-bg px-2 py-1 text-[0.6rem] font-semibold text-hold">PREMIUM</span>}</div><p className="mt-2 text-sm leading-6 text-muted">{deck.description}</p><p className="mt-3 text-xs font-bold text-faint">{deck._count.predictions} predictions · Sort {deck.sortOrder}</p></div><form action={toggleDeck}><input type="hidden" name="id" value={deck.id} /><input type="hidden" name="isActive" value={String(!deck.isActive)} /><button className={`rounded-sharp px-3 py-2 text-xs font-semibold ${deck.isActive ? "bg-blue-wash text-blue" : "bg-line text-muted"}`}>{deck.isActive ? "Active" : "Inactive"}</button></form></div></article>)}</div></div></main>;
}
