import Link from "next/link";
import { getDatabase } from "@/lib/db/client";
import { requireSuperAdmin } from "@/lib/auth/authorization";

export const dynamic = "force-dynamic";

export default async function AdminSettingsPage() {
  await requireSuperAdmin();
  const [admins, settings, auditCount] = await Promise.all([
    getDatabase().user.findMany({ where: { role: { in: ["SUPER_ADMIN", "ADMIN", "EDITOR", "TIPSTER"] } }, select: { id: true, username: true, email: true, role: true, isActive: true, lastLoginAt: true }, orderBy: [{ role: "asc" }, { username: "asc" }] }),
    getDatabase().setting.findMany({ orderBy: [{ group: "asc" }, { key: "asc" }] }),
    getDatabase().auditLog.count(),
  ]);
  const integrations = [["PostgreSQL", true, "Primary application database"], ["Paystack", Boolean(process.env.PAYSTACK_SECRET_KEY), "VIP checkout and payment verification"], ["SMS Gateway", Boolean(process.env.SMS_API_KEY && process.env.SMS_SENDER_ID), "SMS delivery and sender identity"], ["Fixture Sync Cron", Boolean(process.env.CRON_SECRET), "Scheduled fixture and entitlement maintenance"], ["Public App URL", Boolean(process.env.NEXT_PUBLIC_APP_URL), process.env.NEXT_PUBLIC_APP_URL || "Not configured"]] as const;
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-7 sm:py-10"><h1 className="text-3xl font-semibold tracking-[-0.05em] text-ink sm:text-4xl">Settings &amp; Admin Management</h1><div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-sharp border border-line bg-white"><div className="border-b border-line px-5 py-4"><h2 className="text-base font-semibold text-ink">Integration Status</h2></div><div className="divide-y divide-line">{integrations.map(([name, configured, copy]) => <div key={name} className="flex items-center justify-between gap-5 px-5 py-4"><div><p className="text-sm font-semibold text-ink-2">{name}</p><p className="mt-1 text-xs text-faint">{copy}</p></div><span className={`rounded-full px-3 py-1 text-[0.65rem] font-semibold ${configured ? "bg-blue-wash text-blue" : "bg-hold-bg text-hold"}`}>{configured ? "CONFIGURED" : "ACTION NEEDED"}</span></div>)}</div></section><section className="rounded-sharp border border-line bg-white"><div className="flex items-center justify-between border-b border-line px-5 py-4"><h2 className="text-base font-semibold text-ink">Current Admins</h2><Link href="/admin/users" className="text-xs font-semibold text-blue">Manage access</Link></div><div className="divide-y divide-line">{admins.map((admin) => <div key={admin.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><p className="text-sm font-semibold text-ink-2">@{admin.username}</p><p className="mt-1 text-xs text-faint">{admin.email}</p></div><div className="text-right"><span className="text-[0.65rem] font-semibold text-blue">{admin.role.replaceAll("_", " ")}</span><p className="mt-1 text-[0.65rem] text-faint">{admin.isActive ? "Active" : "Inactive"}</p></div></div>)}</div></section></div><section className="mt-6 rounded-sharp border border-line bg-white"><div className="border-b border-line px-5 py-4"><h2 className="text-base font-semibold text-ink">Database Settings</h2></div><div className="divide-y divide-line">{settings.map((setting) => <div key={setting.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[1fr_1.5fr_auto] sm:items-center"><div><p className="text-sm font-semibold text-ink-2">{setting.key}</p><p className="mt-1 text-xs uppercase tracking-wide text-faint">{setting.group}</p></div><code className="overflow-hidden text-ellipsis whitespace-nowrap rounded-sharp bg-paper px-3 py-2 text-xs text-ink-2">{JSON.stringify(setting.value)}</code><span className="text-xs font-bold text-faint">{setting.isPublic ? "Public" : "Private"}</span></div>)}</div><div className="border-t border-line px-5 py-4 text-xs text-faint">{auditCount.toLocaleString()} audit events retained.</div></section></main>;
}
