import Link from "next/link";
import { getDatabase } from "@/lib/db/client";

export const dynamic = "force-dynamic";

function humanize(value: string) {
  return value.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());
}

export default async function NotificationsPage() {
  const [users, activity] = await Promise.all([
    getDatabase().user.count({ where: { isActive: true } }),
    getDatabase().auditLog.findMany({ where: { action: { in: ["BOOKING_SLIP_LOADED", "BOOKING_PUBLISHED", "VIP_MARKED_AVAILABLE", "VIP_MARKED_SOLD_OUT", "PAYMENT_VERIFIED"] } }, include: { actor: { select: { username: true, displayName: true } } }, orderBy: { createdAt: "desc" }, take: 12 }),
  ]);

  return (
    <main className="mx-auto max-w-7xl px-4 pb-8 sm:px-7 sm:pb-10">
      <h1 className="text-3xl font-semibold tracking-[-0.05em] text-ink sm:text-4xl">Notifications</h1>
      <div className="mt-6 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]">
        <section className="rounded-sharp border border-line bg-white p-6"><h2 className="text-lg font-semibold text-ink">Notification Audience</h2><p className="mt-3 text-3xl font-semibold text-blue">{users.toLocaleString()}</p><p className="mt-1 text-sm text-muted">Active registered users</p><p className="mt-5 text-sm leading-6 text-muted">Game availability and purchase updates are generated by the Games and Games Control workflows. A delivery provider must be configured before broadcast notifications can be sent.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/admin/games" className="rounded-sharp bg-[var(--color-blue)] px-4 py-2.5 text-xs font-semibold text-white">Manage Games</Link><Link href="/admin/settings" className="rounded-sharp border border-line px-4 py-2.5 text-xs font-semibold text-ink-2">Open Settings</Link></div></section>
        <section className="overflow-hidden rounded-sharp border border-line bg-white"><div className="border-b border-line px-5 py-4"><h2 className="font-semibold text-ink">Recent Notification Events</h2></div><div className="divide-y divide-line">{activity.map((entry) => <article key={entry.id} className="px-5 py-4"><p className="text-sm font-bold text-ink-2">{humanize(entry.action)}</p><p className="mt-1 text-xs text-faint">{entry.actor?.displayName || entry.actor?.username || "System"} · {entry.createdAt.toLocaleString("en-GB")}</p></article>)}{activity.length === 0 && <p className="p-8 text-center text-sm text-muted">No notification events recorded yet.</p>}</div></section>
      </div>
    </main>
  );
}
