import { getDatabase } from "@/lib/db/client";
import { createPlan, updatePlan } from "./actions";
import { requireManagementAdmin } from "@/lib/auth/authorization";

const input = "mt-2 h-10 w-full rounded-sharp border border-line bg-white px-3 text-sm outline-none focus:border-blue";

export default async function PlansPage() {
  await requireManagementAdmin();
  const [plans, decks] = await Promise.all([getDatabase().plan.findMany({ include: { deck: { select: { name: true } } }, orderBy: { sortOrder: "asc" } }), getDatabase().deck.findMany({ where: { isPremium: true, isActive: true }, orderBy: { sortOrder: "asc" } })]);
  const fields = (plan?: typeof plans[number]) => <><label className="text-sm font-bold text-ink-2">Name<input name="name" required defaultValue={plan?.name} className={input} /></label><label className="text-sm font-bold text-ink-2">Price (GHS)<input name="price" type="number" min="0.01" step="0.01" required defaultValue={plan ? (plan.priceMinor / 100).toFixed(2) : undefined} placeholder="Set current price" className={input} /></label><label className="text-sm font-bold text-ink-2 sm:col-span-2">Description<textarea name="description" required minLength={10} defaultValue={plan?.description} rows={3} className="mt-2 w-full rounded-sharp border border-line p-3 text-sm outline-none focus:border-blue" /></label><label className="text-sm font-bold text-ink-2">Deck<select name="deckId" required defaultValue={plan?.deckId ?? ""} className={input}><option value="">Choose a deck</option>{decks.map((deck) => <option key={deck.id} value={deck.id}>{deck.name}</option>)}</select></label><label className="text-sm font-bold text-ink-2">Sort order<input name="sortOrder" type="number" min="0" defaultValue={plan?.sortOrder ?? 0} className={input} /></label><label className="flex items-center gap-2 text-sm font-bold text-ink-2"><input name="isActive" type="checkbox" defaultChecked={plan?.isActive ?? true} className="size-4 accent-blue" />Show this VIP plan</label><label className="flex items-center gap-2 text-sm font-bold text-lost"><input name="isSoldOut" type="checkbox" defaultChecked={plan?.isSoldOut ?? false} className="size-4 accent-lost" />Mark as sold out</label></>;
  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-14"><h1 className="text-4xl font-semibold tracking-[-0.05em] text-ink">VIP Plans</h1><div className="mt-8 grid gap-6 lg:grid-cols-2"><form action={createPlan} className="h-fit rounded-sharp border border-line bg-white p-6"><h2 className="text-xl font-semibold text-ink">Create Plan</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields()}</div><button className="mt-6 h-11 w-full rounded-sharp bg-[var(--color-blue)] text-sm font-semibold text-white">Create Plan</button></form><div className="space-y-5">{plans.map((plan) => <form key={plan.id} action={updatePlan} className="rounded-sharp border border-line bg-white p-6"><input type="hidden" name="id" value={plan.id} /><div className="grid gap-4 sm:grid-cols-2">{fields(plan)}</div><button className="mt-6 h-11 w-full rounded-sharp bg-ink text-sm font-semibold text-white">Save Changes</button></form>)}</div></div></main>;
}
